### ISSUE TITLE
Tokenizer class PhobertTokenizerFast does not exist or is not currently imported.

### ISSUE THREAD

**Issue by htn274** [VinAIResearch/PhoBERT#25]
![image](https://user-images.githubusercontent.com/26211514/99625810-9a130a00-2a63-11eb-9a8a-0f9b6c71502f.png)
 
First, thank you for your contributions.
I followed your instruction but I got the error. 
Could you help me fix this?
Thanks a lot!

**Comment by datquocnguyen** [comment]
See: https://github.com/VinAIResearch/PhoBERT/issues/21#issuecomment-695881512

**Comment by htn274** [comment]
It doesn't work. I had installed the transformer in older version before I tried your instruction. Does it affect?

**Comment by datquocnguyen** [comment]
Ah right, PhobertTokenizerFast has not implemented yet. However, I have no idea why `transformers` now calls the this *Fast class instead of the original PhobertTokenizer. Each of two solutions should work:

1. Use `PhobertTokenizer` instead of `AutoTokenizer`: 

`from transformers import PhobertTokenizer `
`tokenizer = PhobertTokenizer.from_pretrained("vinai/phobert-base")`

2. Or Install `transformers` version 3.2/3.3

**Comment by datquocnguyen** [comment]
Ah right, PhobertTokenizerFast has not been implemented yet. However, I have no idea why `transformers` now calls this *Fast class instead of the original PhobertTokenizer. Each of the two following solutions should work:

1. Use PhobertTokenizer instead of AutoTokenizer:

    from transformers import PhobertTokenizer 
    tokenizer = PhobertTokenizer.from_pretrained("vinai/phobert-base")

2. Or Install transformers version 3.2/3.3

**Comment by htn274** [comment]
![image](https://user-images.githubusercontent.com/26211514/99929151-b1f9cf00-2d7e-11eb-942e-637f140cb0bd.png)
I am trying to add Phobert to the [JointBert model](https://github.com/monologg/JointBERT). 
I got the error. 
Could you explain why and help me fix it? 
Thanks a lot!
